// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebAppUserInterfaceCultuurplein1db.data.WebAppUserInterfaceCultuurplein1
{
    // Data set aangemaakt voor het opvullen van de database en het weergeven van data.
    public partial class Shows
    {
        public int Id { get; set; }
        public string Voorstelling { get; set; }
        public string Beschrijving { get; set; }
        public byte[] Afbeelding { get; set; }
    }
}